del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\asm\asmb.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\boot\head32.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\boot\multiboot.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\cpu\cpu.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\drivers\block\floppy.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\drivers\block\ll_rw_block.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\drivers\bus\pci.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\drivers\char\tty.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\block_dev.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\buffer.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\dcache.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\devices.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\exec.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\inodes.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\ioctl.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\mount.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\namei.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\open.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\read_write.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\super_bloque.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\fat\files.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\fat\inodes.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\fat\misc.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\filesystem\fat\super.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\gdt\gdt.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\int\excepciones.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\int\idt.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\int\irq.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\kernel\dma.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\kernel\init.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\kernel\kdev.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\kernel\kernel.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\kernel\printk.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\kernel\syscall.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\Lib\fpclib\fpclib.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\Lib\fpclib\strings.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\memoria\malloc.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\memoria\mapmem.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\memoria\mm.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\memoria\paging.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\memoria\vmalloc.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\itimer.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\ktimer.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\procesos.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\relog.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\scheduler.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\signal.o
del c:\TORO\Src\TORO\CVS\CvsTra\toro-src\usr\toro-src\procesos\sys_procesos.o
